### ISSUE TITLE
Architecture for Objects, Directory Structure and API

### ISSUE THREAD

**Issue by rsweetland** [rsweetland/Lean-Charts#5]
Per our Skype chat, the next steps are to:
- Design / sketch out the entities / object graph
- Design new directory structure (if needed).
- Design new API (if needed)

Looking forward to seeing how we can restructure things here!

**Comment by phpfour** [comment]
**Theory of Operation**

Application-level events are triggered using an instance of the Log class. These events are stored in the Log table. Every hour and every day a cron script is run to process this table, generating useful statistics based off of this data. 

Change-log events are entered separately and manually by the application-owner / data scientist / product manager / etc for purposes of correlating the change-log events to these statistics.

The Dashboard shows a grid of line-graphs, plotting the values of the statistics over time. Change-log events are cross-referenced on these charts so that the effects of changes on each statistic can be can be easily viewed.

By default the Dashboard will show the frequency of application events logged over time. The application owner can add custom statistics by adding custom code to the “custom stats” directory and following the API conventions below. 

Finally, there is alert system where an alert if fired if a statistic shows irregular activity. This can be used to send emails, roll back a change, etc.

**Entities**
- Event - Event ID, Name, Weight, Send Alert
- Log Entry - Log ID, Event ID, Date, Object ID, Object Type, User ID, Num Value, Data
- Stat - Event ID, Value
- Change Log - ChangeLog ID, Title, Description, Date
- Alert - Alert ID, Event ID, Date, Type
